services:
  config-server:
    image: springcommunity/spring-petclinic-config-server
    environment:
      - SPRING_PROFILES_ACTIVE=native,docker
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./config-repo:/config-repo
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://config-server:8888" ]
      interval: 5s
      timeout: 5s
      retries: 10

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761" ]
      interval: 5s
      timeout: 3s
      retries: 10

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy

  genai-service:
    image: springcommunity/spring-petclinic-genai-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy


  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8080:8080"

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8090:8090"

  loki:
    image: grafana/loki:main
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "3200:3200"  # Tempo
      - "9411:9411" # zipkin

  ## Grafana / Prometheus
  prometheus:
    image: prom/prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "3000:3000"
