services:
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=native,docker
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./config-repo:/config-repo
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://config-server:8888" ]
      interval: 5s
      timeout: 5s
      retries: 10

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761" ]
      interval: 5s
      timeout: 3s
      retries: 10

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8085:8085"

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8082:8082"

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8083:8083"

  genai-service:
    image: springcommunity/spring-petclinic-genai-service
    container_name: genai-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8084:8084"


  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8080:8080"

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8090:8090"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://zipkin:9411" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ## Grafana / Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "3000:3000"
