spring:
  application:
    name: genai-service

spring.config.import: optional:configserver:http://localhost:8888/,optional:classpath:/creds.yaml

---
spring.config.activate.on-profile: docker

spring.config.import: configserver:http://config-server:8888



